animations {
    enabled = true

    bezier = easeOut, 0.05, 0.9, 0.1, 1.05
    bezier = easeInOut, 0.45, 0, 0.55, 1
    bezier = smooth, 0.25, 0.1, 0.25, 1

    animation = windows, 1, 7, easeOut
    animation = windowsIn, 1, 7, easeOut
    animation = windowsOut, 1, 6, easeInOut
    animation = border, 1, 8, smooth
    animation = fade, 1, 6, smooth
    animation = workspaces, 1, 7, easeOut
}