# Bars / notifications
exec-once = pkill waybar; waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css
exec-once = pkill swaync; swaync

# Wallpaper
exec-once = pkill hyprpaper; hyprpaper

# Optional applets / agents
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1