background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 6
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2

    outer_color = rgb(8b5cf6)
    inner_color = rgb(111827)
    font_color = rgb(e5e7eb)

    fade_on_empty = false
    rounding = 12

    placeholder_text = <i>Enter Password</i>
}

label {
    monitor =
    text = Hi $USER
    font_size = 22
    color = rgb(e5e7eb)

    position = 0, 80
    halign = center
    valign = center
}