# =========================
# Arch Neon Kitty Config
# =========================

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0

# Cursor
cursor_shape block
cursor_blink_interval 0.5

# Window
background_opacity 0.90
confirm_os_window_close 0

# Padding
window_padding_width 10

# Tabs
tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 1

# Colors (neon dark)
foreground #e5e7eb
background #0b0f17

selection_foreground #000000
selection_background #22d3ee

cursor #8b5cf6

# black
color0  #111827
color8  #374151

# red
color1  #ef4444
color9  #f87171

# green
color2  #22c55e
color10 #4ade80

# yellow
color3  #facc15
color11 #fde047

# blue
color4  #3b82f6
color12 #60a5fa

# magenta
color5  #8b5cf6
color13 #a78bfa

# cyan
color6  #22d3ee
color14 #67e8f9

# white
color7  #e5e7eb
color15 #f9fafb

# Scrollback
scrollback_lines 10000

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes